// // app/layout.jsx
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast"; // Importe o Toaster

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         suppressHydrationWarning
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <Toaster
//           position="top-right" // Posição do toast
//           toastOptions={{
//             duration: 3000, // Duração em milissegundos
//             style: {
//               background: "#10B981", // Verde para sucesso
//               color: "#fff", // Texto branco
//               fontSize: "16px",
//             },
//           }}
//         />
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomToaster from "@/components/CustomToaster"; // importa o custom

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gerenciador de Estoque",
  description: "Sistema para loja de calçados",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <CustomToaster /> {/* só ele, nada de Toaster direto */}
      </body>
    </html>
  );
}
